import { TimeTableRow } from "./types"

export const sampleTimeTableRows: TimeTableRow[] = [
  {
    asset_id: "AST-001",
    project: "Marina Vista",
    area: "dubai marina",
    developer: "Emaar",
    price_from_aed: 1850000,
    yield_pct: 6.2,
    risk_band: "Capital Safe",
    liquidity_band: "Short (1-2yr)",
    status_band: "Completed",
    handover_date: "2024-06-01",
    gfa_sqm: 140,
  },
  {
    asset_id: "AST-014",
    project: "Palm Crest",
    area: "palm jumeirah",
    developer: "Nakheel",
    price_from_aed: 3250000,
    yield_pct: 5.4,
    risk_band: "Institutional Safe",
    liquidity_band: "Medium (2-4yr)",
    status_band: "2026",
    handover_date: "2026-09-01",
    gfa_sqm: 210,
  },
  {
    asset_id: "AST-028",
    project: "JVC Heights",
    area: "JVC",
    developer: "Sobha",
    price_from_aed: 980000,
    yield_pct: 7.1,
    risk_band: "Opportunistic",
    liquidity_band: "Short (1-2yr)",
    status_band: "2025",
    handover_date: "2025-03-01",
    gfa_sqm: 95,
  },
  {
    asset_id: "AST-042",
    project: "Downtown Edge",
    area: "downtown",
    developer: "Dubai Properties",
    price_from_aed: 2450000,
    yield_pct: 5.9,
    risk_band: "Capital Safe",
    liquidity_band: "Medium (2-4yr)",
    status_band: "2027",
    handover_date: "2027-12-01",
    gfa_sqm: 160,
  },
  {
    asset_id: "AST-055",
    project: "Business Bay Rise",
    area: "business bay",
    developer: "Select",
    price_from_aed: 1550000,
    yield_pct: 6.6,
    risk_band: "Capital Safe",
    liquidity_band: "Short (1-2yr)",
    status_band: "2026",
    handover_date: "2026-06-01",
    gfa_sqm: 120,
  },
]
