import type { InventoryRow, MarketScoreCharts, MarketScoreSummary } from "@/lib/market-score/types"

export const DEMO_MARKET_SCORE_SUMMARY: MarketScoreSummary = {
  totalAssets: 24730,
  avgScore: 71.6,
  safetyDistribution: [
    { label: "Institutional Safe", count: 8200 },
    { label: "Capital Safe", count: 9900 },
    { label: "Opportunistic", count: 5200 },
    { label: "Speculative", count: 1430 },
  ],
  classificationDistribution: [
    { label: "Conservative", count: 11000 },
    { label: "Balanced", count: 9000 },
    { label: "Aggressive", count: 3600 },
    { label: "Speculative", count: 1130 },
  ],
  avgScoreByStatus: [
    { label: "Completed", avgScore: 76.2 },
    { label: "2025", avgScore: 73.1 },
    { label: "2026", avgScore: 70.4 },
    { label: "2027", avgScore: 66.5 },
    { label: "2028-29", avgScore: 62.8 },
    { label: "2030+", avgScore: 58.9 },
  ],
  avgScoreBySafetyBand: [
    { label: "Institutional Safe", avgScore: 80.4 },
    { label: "Capital Safe", avgScore: 74.6 },
    { label: "Opportunistic", avgScore: 66.1 },
    { label: "Speculative", avgScore: 57.3 },
  ],
  conservativeReadyPool: 7400,
  balancedDefaultPool: 5100,
  available: {
    cities: ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Ras Al Khaimah", "Fujairah"],
    areas: [
      "Business Bay",
      "Dubai Marina",
      "Downtown Dubai",
      "Jumeirah Village Circle",
      "JBR",
      "Dubai Hills",
    ],
    statusBands: ["Completed", "2025", "2026", "2027", "2028-29", "2030+"],
    priceTiers: ["Entry", "Mid", "Premium", "Ultra"],
    safetyBands: ["Institutional Safe", "Capital Safe", "Opportunistic", "Speculative"],
  },
  source: "view",
  truthChecks: {
    conservativeReady: [],
    balancedShort: [],
    horizonViolations: 0,
    speculativeLeak: 0,
  },
  healthcheck: null,
}

export const DEMO_MARKET_SCORE_CHARTS: MarketScoreCharts = {
  safetyDistribution: DEMO_MARKET_SCORE_SUMMARY.safetyDistribution,
  avgScoreByStatus: DEMO_MARKET_SCORE_SUMMARY.avgScoreByStatus,
  avgScoreBySafetyBand: DEMO_MARKET_SCORE_SUMMARY.avgScoreBySafetyBand,
  avgScoreByPriceTier: [
    { label: "Entry", avgScore: 74.2 },
    { label: "Mid", avgScore: 71.5 },
    { label: "Premium", avgScore: 68.3 },
    { label: "Ultra", avgScore: 64.7 },
  ],
  countByCity: [
    { label: "Dubai", count: 16800 },
    { label: "Abu Dhabi", count: 4200 },
    { label: "Sharjah", count: 2400 },
    { label: "Ajman", count: 1330 },
  ],
  source: "view",
}

export const DEMO_DASHBOARD = {
  source: "snapshot",
  overview: {
    total_projects: 7800,
    portfolio_value: 68500000000,
    avg_price: 1950000,
    avg_yield: 6.8,
    avg_appreciation: 7.4,
  },
  market_health: {
    undersupplied_pct: 18.4,
    high_confidence_pct: 42.2,
    avg_liquidity: 74.1,
  },
  top_areas_by_yield: [
    { label: "Jumeirah Village Circle", value: 7.2 },
    { label: "Business Bay", value: 6.8 },
    { label: "Dubai Marina", value: 6.4 },
  ],
  alerts: [
    "Downtown Dubai pricing stabilized after Q2 absorption.",
    "Dubai Hills off-plan demand accelerated in the last 30 days.",
    "JBR rental compression easing in core towers.",
  ],
} as const

export const DEMO_LIBRARY_ROWS: InventoryRow[] = [
  {
    asset_id: "DXB-1024",
    name: "Marina Vista Tower",
    developer: "Emaar",
    city: "Dubai",
    area: "Dubai Marina",
    status_band: "2025",
    price_aed: 1850000,
    beds: 2,
    score_0_100: 78,
    match_score: null,
    final_rank: null,
    safety_band: "Capital Safe",
    classification: "Balanced",
    roi_band: "6-7%",
    liquidity_band: "High",
    timeline_risk_band: "Low",
    drivers: null,
    warnings: null,
    reason_codes: null,
    risk_flags: null,
  },
  {
    asset_id: "DXB-2177",
    name: "Business Bay Crest",
    developer: "Select Group",
    city: "Dubai",
    area: "Business Bay",
    status_band: "Completed",
    price_aed: 1290000,
    beds: 1,
    score_0_100: 74,
    match_score: null,
    final_rank: null,
    safety_band: "Institutional Safe",
    classification: "Conservative",
    roi_band: "6-6.5%",
    liquidity_band: "High",
    timeline_risk_band: "Low",
    drivers: null,
    warnings: null,
    reason_codes: null,
    risk_flags: null,
  },
  {
    asset_id: "DXB-3341",
    name: "Dubai Hills Park",
    developer: "Emaar",
    city: "Dubai",
    area: "Dubai Hills",
    status_band: "2026",
    price_aed: 2450000,
    beds: 3,
    score_0_100: 69,
    match_score: null,
    final_rank: null,
    safety_band: "Opportunistic",
    classification: "Balanced",
    roi_band: "5.5-6%",
    liquidity_band: "Medium",
    timeline_risk_band: "Medium",
    drivers: null,
    warnings: null,
    reason_codes: null,
    risk_flags: null,
  },
]

export const DEMO_MARKET_RESULTS = [
  {
    asset_id: "DXB-1024",
    name: "Marina Vista Tower",
    developer: "Emaar",
    city: "Dubai",
    area: "Dubai Marina",
    status_band: "2025",
    price_aed: 1850000,
    beds: "2",
    score_0_100: 78,
    safety_band: "Capital Safe",
    classification: "Balanced",
  },
  {
    asset_id: "DXB-2177",
    name: "Business Bay Crest",
    developer: "Select Group",
    city: "Dubai",
    area: "Business Bay",
    status_band: "Completed",
    price_aed: 1290000,
    beds: "1",
    score_0_100: 74,
    safety_band: "Institutional Safe",
    classification: "Conservative",
  },
  {
    asset_id: "DXB-3341",
    name: "Dubai Hills Park",
    developer: "Emaar",
    city: "Dubai",
    area: "Dubai Hills",
    status_band: "2026",
    price_aed: 2450000,
    beds: "3",
    score_0_100: 69,
    safety_band: "Opportunistic",
    classification: "Balanced",
  },
] as const
