import { NextResponse } from "next/server"
import { getSessionUser } from "@/lib/auth/server"
import { prisma } from "@/lib/prisma"

export const dynamic = "force-dynamic"

export async function POST(
  _req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params

  const user = await getSessionUser()
  if (!user?.id || !user.email) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  const report = await prisma.assistantReport.findFirst({
    where: { id, userId: user.id },
    select: { id: true, publicId: true, title: true },
  })

  if (!report) {
    return NextResponse.json({ error: "Not found" }, { status: 404 })
  }

  const apiKey = process.env.RESEND_API_KEY
  if (apiKey) {
    try {
      const { Resend } = await import("resend")
      const resend = new Resend(apiKey)
      const origin = process.env.NEXT_PUBLIC_APP_URL ?? "https://app.entrestate.com"
      const reportUrl = `${origin}/reports/${report.publicId}`

      await resend.emails.send({
        from: "Entrestate <reports@entrestate.com>",
        to: user.email,
        subject: `Your report is ready: ${report.title}`,
        html: `
          <div style="font-family: system-ui, sans-serif; max-width: 560px; margin: 0 auto; padding: 40px 24px; color: #e2e8f0; background: #0d1117;">
            <div style="margin-bottom: 32px;">
              <div style="display: inline-flex; gap: 4px; margin-bottom: 16px;">
                <div style="width: 10px; height: 10px; border-radius: 2px; background: #f8fafc;"></div>
                <div style="width: 10px; height: 10px; border-radius: 2px; background: rgba(248,250,252,0.5);"></div>
                <div style="width: 10px; height: 10px; border-radius: 2px; background: #14b8a6;"></div>
              </div>
              <h1 style="font-size: 22px; font-weight: 600; color: #f8fafc; margin: 0 0 8px;">Your report is ready</h1>
              <p style="color: #64748b; font-size: 14px; margin: 0;">Generated by Entrestate Decision Intelligence</p>
            </div>
            <div style="border: 1px solid #1e293b; border-radius: 12px; padding: 20px 24px; margin-bottom: 28px; background: #0f172a;">
              <p style="font-size: 13px; color: #64748b; margin: 0 0 6px; text-transform: uppercase; letter-spacing: 0.05em;">Report</p>
              <p style="font-size: 16px; font-weight: 600; color: #f1f5f9; margin: 0;">${report.title}</p>
            </div>
            <a href="${reportUrl}" style="display: inline-block; background: #14b8a6; color: #fff; text-decoration: none; font-size: 14px; font-weight: 600; padding: 12px 24px; border-radius: 8px; margin-bottom: 24px;">
              Open Report →
            </a>
            <p style="font-size: 12px; color: #334155; margin: 0;">
              You're receiving this because you requested it via Entrestate.<br/>
              <a href="${origin}/account/reports" style="color: #475569;">View all your reports</a>
            </p>
          </div>
        `,
      })
    } catch (err) {
      console.error("Email send failed:", err)
      // Still return ok — don't fail the user request
    }
  }

  return NextResponse.json({ ok: true })
}
